server:
    port: 8081
    servlet:
        context-path: /artemio
spring:
    application:
        name: vg.ms.student
    data:
        mongodb:
            uri: mongodb+srv://amirarbieto:n1230IGFtm6682Kj@artemiosolutions.pripjnm.mongodb.net/artemiosolutions?retryWrites=true&w=majority